package Enum;

public enum ContrainteLevel
{
	NB_PIECES_2,
	NB_PIECES_3,
	NB_PIECES_4,
	NB_PIECES_5,
	NB_PIECES_RECTO_2,
	NB_PIECES_RECTO_3,
	NB_PIECES_RECTO_4,
	NB_PIECES_RECTO_5,
	PIECE_PRESENTE_I,
	PIECE_PRESENTE_O,
	PIECE_PRESENTE_T,
	PIECE_PRESENTE_L,
	PIECE_PRESENTE_S
}
